services:
   app:
    build:
      context: .
      dockerfile: dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: APP
      DB_PASSWORD: admin
      DB_NAME: db
      SALT: 10
      TOKEN_SECRET: e1cc452bdb38dd6e6321789389d10f9f51438232b5eaa12d7eb8c4d9dfd56486b065075c398a833eb96af2942acb47c9e1978f67d36d588f48d2d6ebff17bb5c
    ports:
      - "3000:3000"